language: node_js
node_js:
  - 10
  - 12
  - node
os:
  - linux
branches:
  only:
  - master
  - /^v.*$/

env:
  global:
    - secure: DEfXuBWNAvru3+/2UOLJH0ea4BX/Wzr8hLVvcRmZv5usbNhgn0lmnGXySWSA5HuutQddQanTxBo9fAzVh7RejdBshHxN77WuwHQFstC2igVhNWafTF9jPlOIFHgqT0Cc8Kc9EKhUB1r6FcWwtixtaFRuhisumU2dS/jPiMJZx9ekO9hoUyZA1Ka0eu8oextFWPNS0MDgUOWZEAgOBFsRTwuQAcDM/nTMlmoFfiM9k4BSvQ5IdlmCkZgEwVUXNqHWh/Ic6QGMkE51lGaka46jEu0QLGvljTLPFzDsaCpknBa9+lpxFUmfR6LqOkKbXW3W+xef9tiJEFYh8iSZleNXodYnt3AmhNGtbEb0/8IEQrjfkxPR5gK6qNfNDyYE82qyYwTv1jS4sHNJwspAHnf0L0WuM4JHI8Gx3qdZpic1t/FmEJFZOWZd1UZ8GP6gJe2CUt+5MdDGeU4omstJR83EJcnEJHR8tqpC21Fww/gSxb1sLra4UX4QcndSfo1WZUXiF2+7rqNs0821PkYFOSczeJ49GrWGaUlJ6G9fI9x5PDDHVgEdJmc/KhG32jCTs002h465hjCLiXAKfTVYsYR/y4U0Y/BPzap3jiTXHfEOs/7WQN2LwmbfOiRj5zZWWq5x9NijMHonFKlpMo/0BQYhL0t2wNs1WFZ7HqwhfWqFwzU=
    - secure: cThAmdUjaGkRxwRA4mOuTUsfUVHJ1jBqOW3x/tdCysF7hd6qp/YSWVl/6DWF3IWGiII3U9oVTVEzTATcRHn9z2Hyi6jHiOD62Yqab8x8nA1IVzzTMT1AnPqDHb1VC0gVfdiHDzYLAJWxv+pQvmcN/Z0kvIVR4CqoQPpTQtFN8xJEDxYCN2c6jdB3I5MPfKKmsRfb05ZHDbTCxSJVmCJTcr+aXBzM67AoKNHgTwQn2TJqlQlKnJRC0zjyFKzLYGQZ51GyDhqgUE8qlhsdXyaaBaHJxiKWnGT/3XWNvJaynVy1TAvWIQqtH/vSWj6DVwYAzOIBaYuRbjuwCj1RJoL23c/xqW+WhEoocxwtGZirWS6SAl0+woPeX1FJGz34dirvs8wIs4PdNtaSdTx6IHQRh8p0UeCd5kAsD8tKhH3+cAj6hjzIC5ticEWmYviYK4QvR4ftj0S37QXxGhXoWjFKNy03xIACUyF1XYspK58gSCdtZfGw5Q2aR+qJnFO+YczNA4SgQ+Nrol40zuSePduKdCWQRCr63TBUo9qMHt1tJ7xNuIBbNL/S973KZiDU70R4tFqAIrec98ZckT8ll8BQgnMp8AwHiwkZyIH2lmZT34RiDlQ33s4f42OaFAQuknY3dG/u5sFn7qfGL+9rOGsZtyGbMZgVhzm4Ros87SMVVHI=
    - secure: ijXfPbA5bouViUvdTqJG/SKoRb2pBG2SstONvsFSanDt6tf6tx860FFhQCzH4uiDVqSyuV+UXPzvh1+HK8iKeSa8iaPITrfZ0sapun2wO3zwi1Ms+7YZlwS0lh8/2+CAKUecM1l4+K6V3DAjKKAzMVtZR4ay9L9xqabRF8cYaEi5hiAGHwGL60aQcH3oJscQ757TZWe40JkKZyaz5BGuyc7gDCObK/SgHbuinCznaAIMfeD+SljLSVpllB4zkCvGIbd5yqu6TDg5a643GuAVBZFYvAXo1X2tk3QAo9QD020uG6WhPqF+O3swwGqZzR7fFhI3X0wexwZk4UaGwSyKM4GnCVwsB3AyvlHR7O5C3w1U8Ll7Dj7RbVVHDwYKEZq5e5CWbU9x8HMukScvUWT8V5itSQA3KgsV19r6OBglOhLSZoN+TX9dOGztqtvW5ShF1k57by9gEoYEFFFUJdr8xj92SIDakcoe+SVDP/nqEKnvKWIQ9U1z8jcUS0883YzCtzdNo0WpE2rHNyen5VPkxe6dhoOPvILAbUW8V2Q9zah1HHinM00loz19/fsOE+K0t+vpdK6PJhWi6JLTAAhS9v4AM3OD+IJyAdOAgA8CTqeytGX0sEH7V+lfFRRnUTl4LbhEdGqT1WgvLydo/C9hiroDV/xzyEdvyx5zr46PoDc=

install:
  - npm ci
script:
  # Avoid failing tests because of slow network
  - export REQUEST_TIMEOUT=20000
  # First run a normal test pass
  - TESTING=true npm test
  # Also make sure that the template creation does not fail
  - bash travis/test_template_creation.sh

  # Then test on a production environment
  # Therefore build the project
  - npm run build
  # Remove all dev dependencies
  - npm ci --only=production
  # Test if the CLI starts up without any errors
  - TEST_STARTUP=true npx .
  # TODO: Test the console output

jobs:
  include:
    - # Only deploy on versioned tags (created by npm run release ...)
      if: (tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+/)
      stage: deploy
      node_js: "12"
      install: npm ci
      script: skip
      deploy:
        provider: npm
        # Opt in to deploy v2 which fixes some issues
        # https://docs.travis-ci.com/user/deployment-v2#how-to-opt-in-to-v2
        edge: true 
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true # This must be true or tags won't be released
    - # Update the ioBroker.template repo always (for now)
      stage: deploy
      node_js: "12"
      install: npm ci
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash travis/update_templates.sh
        on:
          tags: true

notifications:
  email: false
